# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: Pablo Toledo Gavagnin

# If you are using a corportive proxy you need:
# - Install proxy plugin for Vagrant
#       vagrant plugin install vagrant-proxyconf
# - Run Vagrant using enviroment variables for Vagrant:
#       VAGRANT_HTTP_PROXY="http://proxy:port" VAGRANT_HTTPS_PROXY="http://proxy:port" vagrant up

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  # Docker EE node for CentOS 7.3
    config.vm.define "centos7" do |centos7vm|
      centos7vm.vm.box = "centos/7"
      #centos7vm.vm.network "private_network", type: "dhcp"
      config.vm.network "private_network", ip: "192.168.10.10"
      centos7vm.vm.hostname = "centos7"
      config.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", "4096"]
         vb.customize ["modifyvm", :id, "--cpus", "2"]
         vb.name = "centos7"
      end
    end

end
